In [ ]:
# Numpy Crash Course

In [1]:
import numpy as np 

In [2]:
np.__version__

'2.4.6'

In [3]:
import sys 
sys.version

'3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]'

## Creating LIST

In [4]:
my_list = [0,1,2,3,4,5]
my_list 

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

# below code we are converting list to array

In [6]:
#!pip install numpy

In [7]:
arr = np.array(my_list) 

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [ ]:
np. # we learn important function 

In [9]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5.0)   

array([0., 1., 2., 3., 4.])

In [11]:
np.arange(9) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.arange(0, 5) 

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [15]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [18]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [ ]:
ar = np.arange(-30,20)
ar

In [19]:
np.arange(10,10) 

array([], dtype=int64)

In [20]:
np.arange()

TypeError: arange() requires stop to be specified.

In [21]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [23]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [24]:
np.zeros(10) # parameter  tunning 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [26]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [27]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

In [30]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.zeros((2,12),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [36]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [52]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [55]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [56]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [57]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [61]:
print(np.zeros(n1,dtype=int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [62]:
c = (5,6)
print(np.zeros(c,dtype=int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [63]:
np.zeros((4,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [64]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
n

In [65]:
n1

(6, 8)

In [66]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [67]:
print(np.zeros(n1,dtype=int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [68]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [70]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [72]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [73]:
np.ones(4)

array([1., 1., 1., 1.])

In [75]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [76]:
n

(6, 7)

In [77]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [78]:
print(np.ones(n,dtype=int))

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [79]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.

In [80]:
np.two((2,3)) 

AttributeError: module 'numpy' has no attribute 'two'

In [ ]:
np.three(2,3) 

In [81]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones((2,4)) 

In [ ]:
np.ones((6,10),dtype = int) 

In [ ]:
np.twos((2,4))

In [ ]:
np.

In [ ]:
np.three((2,4))

In [82]:
range(5)

range(0, 5)

In [83]:
r = range(5)
r

range(0, 5)

In [93]:
for i in r:
    print(i)

0
1
2
3
4


In [84]:
list(range(5))

[0, 1, 2, 3, 4]

In [85]:
range(1,10)

range(1, 10)

In [86]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [87]:
list(range(7,14))

[7, 8, 9, 10, 11, 12, 13]

In [88]:
tuple(range(6,10))

(6, 7, 8, 9)

In [ ]:
list(range(1,10,3))

In [89]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [90]:
rand(3,2)

NameError: name 'rand' is not defined

In [91]:
random.rand(3,2)

NameError: name 'random' is not defined

In [92]:
np.random.rand(5)

array([0.5574153 , 0.459315  , 0.81590087, 0.3265471 , 0.4958233 ])

In [ ]:
np.rand(4)

In [94]:
np.random.rand(3,5)

array([[0.970552  , 0.07642853, 0.60215786, 0.08718779, 0.93960445],
       [0.14280425, 0.17186535, 0.94378888, 0.15127678, 0.13390659],
       [0.16420064, 0.57858429, 0.53265447, 0.45281957, 0.29522438]])

In [95]:
np.random.randint(4,6)

4

In [96]:
np.random.randint(2,20,4) # 2nd argument is exlusive 

array([ 8,  8, 12,  7], dtype=int32)

In [99]:
np.random.randint(0,1) 

0

In [100]:
np.random.randint(10,20,5)

array([13, 17, 11, 17, 13], dtype=int32)

In [101]:
np.random.randint(1,6,4)

array([5, 2, 2, 5], dtype=int32)

In [ ]:
np.random.rand(3)

In [ ]:
np.random.randint(1)  

In [ ]:
np.random.randint(30,20,10) 

In [ ]:
np.random.randint(-30,20,10) 

In [106]:
np.random.randint(20,30,10) 

array([26, 26, 23, 23, 21, 21, 21, 23, 27, 27], dtype=int32)

In [105]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

6

In [ ]:
np.random.randint(10,21,3)

In [ ]:
np.random.randint(1,12,10)

In [107]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[11, 37, 11, 27, 33, 11, 28, 19, 21, 28],
       [21, 31, 30, 28, 26, 29, 30, 26, 17, 11],
       [35, 16, 25, 26, 12, 28, 36, 21, 25, 13],
       [17, 36, 31, 26, 36, 39, 23, 23, 36, 30],
       [11, 30, 25, 24, 17, 17, 16, 27, 25, 21],
       [38, 10, 21, 10, 13, 22, 10, 19, 20, 16],
       [13, 34, 14, 25, 32, 21, 38, 17, 24, 19],
       [33, 35, 12, 38, 11, 26, 10, 18, 31, 21],
       [38, 18, 34, 19, 20, 22, 25, 18, 30, 30],
       [21, 24, 35, 26, 13, 32, 23, 16, 31, 27]], dtype=int32)

In [ ]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

In [ ]:
np.arange(1,13)

In [ ]:
np.arange(1,13).reshape(3,4)

In [ ]:
np.arange(1,13).reshape(4,3)

In [ ]:
np.arange(1,13).reshape(5,4)

In [ ]:
np.arange(1,13).reshape(6,2)

In [ ]:
np.arange(1,13).reshape(12,1)

# slicing in matrix

In [37]:
b = np.random.randint(10,20,(5,4))
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [ ]:
type(b)

In [38]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [39]:
b[:] 

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [40]:
b[1:3]

array([[16, 12, 15, 18],
       [19, 14, 11, 10]], dtype=int32)

In [41]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [42]:
b[1,2]

np.int32(15)

In [ ]:
b

In [43]:
b[1,3]

np.int32(18)

In [108]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [44]:
b[1,-1]

np.int32(18)

In [45]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [46]:
b[2:3]

array([[19, 14, 11, 10]], dtype=int32)

In [109]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [110]:
b[0:-2] 

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10]], dtype=int32)

In [111]:
b[0:-3]

array([[19, 17, 19, 15],
       [16, 12, 15, 18]], dtype=int32)

In [112]:
b[0:-1]

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11]], dtype=int32)

In [113]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [47]:
b[0,2] 

np.int32(19)

In [48]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [114]:
b[-5,3] 

np.int32(15)

In [115]:
b[-5,-3]

np.int32(17)

In [ ]:
b

In [51]:
b[-4,2] 

np.int32(15)

In [117]:
np.random.randint(10,20,(4,4))

array([[16, 17, 19, 16],
       [10, 19, 17, 15],
       [11, 12, 10, 18],
       [13, 14, 13, 11]], dtype=int32)

In [116]:
b 

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [123]:
b[3]

array([10, 16, 10, 11], dtype=int32)

In [124]:
b[3:5]

array([[10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [126]:
b[2,-2]

np.int32(11)

In [125]:
b[2,2]

np.int32(11)

In [118]:
b[-4,-2]

np.int32(15)

In [119]:
b

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

In [120]:
b[-4:2] 

array([[16, 12, 15, 18]], dtype=int32)

In [121]:
b[-4:3]

array([[16, 12, 15, 18],
       [19, 14, 11, 10]], dtype=int32)

In [122]:
b[:]

array([[19, 17, 19, 15],
       [16, 12, 15, 18],
       [19, 14, 11, 10],
       [10, 16, 10, 11],
       [16, 14, 14, 14]], dtype=int32)

## Operations

In [127]:
a = np.random.randint(10,20,10)
a

array([17, 14, 16, 18, 10, 12, 15, 10, 18, 15], dtype=int32)

In [130]:
k = np.random.randint(50,70,(4,5))
k
print(k)

[[56 50 60 51 53]
 [65 65 52 52 59]
 [52 55 62 68 65]
 [50 69 53 68 57]]


In [133]:
print(k[1:3,1:3])


[[65 52]
 [55 62]]


In [134]:
id(a)

2607680640304

In [135]:
arr

array([0, 1, 2, 3, 4, 5])

In [136]:
arr2 = np.random.randint(0,100,(10,10))

In [137]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [138]:
arr

array([0, 1, 2, 3, 4, 5])

In [139]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr

In [140]:
arr[:4] 

array([0, 1, 2, 3])

In [141]:
arr2[:]

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [142]:
arr2[0:5] 

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71]], dtype=int32)

In [143]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [144]:
arr2[1,4] 

np.int32(10)

In [145]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [146]:
arr2[-5,5] 

np.int32(38)

In [147]:
arr2[-5,-5] 

np.int32(38)

In [ ]:
arr2

In [ ]:
arr2[-5,-5]

In [148]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [149]:
arr2[-1,-2]

np.int32(78)

In [150]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [151]:
arr2[::-1]

array([[82, 62, 55, 66, 57, 33, 16, 61, 78, 51],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [71, 81, 39,  7, 97, 37, 23, 83, 50, 50]], dtype=int32)

In [152]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [153]:
arr2[::-2] 

array([[82, 62, 55, 66, 57, 33, 16, 61, 78, 51],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67]], dtype=int32)

In [154]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [155]:
arr2[::-3]

array([[82, 62, 55, 66, 57, 33, 16, 61, 78, 51],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [71, 81, 39,  7, 97, 37, 23, 83, 50, 50]], dtype=int32)

In [156]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [157]:
arr2[:-3] 

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42]], dtype=int32)

In [158]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [159]:
arr2[0:10:3]

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [160]:
arr2

array([[71, 81, 39,  7, 97, 37, 23, 83, 50, 50],
       [77, 41, 65, 21, 10, 38, 60, 24, 27, 67],
       [50, 79, 99, 30, 17,  5, 92, 80, 70, 80],
       [11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [161]:
arr2[3:]

array([[11, 27, 23, 79, 90, 30, 75,  2, 16, 25],
       [93, 18, 42, 35,  6,  3, 90, 50, 14, 71],
       [38, 72, 77, 29, 62, 38, 47, 13, 69, 76],
       [11, 66, 70, 21, 35, 60,  2, 63, 46, 42],
       [40, 70, 91, 93, 77, 29, 65, 20, 78, 63],
       [54, 94, 93, 52,  7, 18, 86,  5, 45, 31],
       [82, 62, 55, 66, 57, 33, 16, 61, 78, 51]], dtype=int32)

In [162]:
arr

array([0, 1, 2, 3, 4, 5])

In [163]:
arr.max() 

np.int64(5)

In [164]:
arr.min()

np.int64(0)

In [165]:
arr

array([0, 1, 2, 3, 4, 5])

In [166]:
arr.mean()

np.float64(2.5)

In [167]:
arr

array([0, 1, 2, 3, 4, 5])

In [168]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [169]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [173]:
e = array([1,2,3,4,5,6,7])
e
mean(e)
median(e)

np.float64(4.0)

In [175]:
e
median(e)

np.float64(4.0)

In [176]:
f = array([1,2,3,4,5,6,7,8])
print(f)

[1 2 3 4 5 6 7 8]


In [177]:
print(mean(f))

4.5


In [178]:
print(median(f))

4.5


# Without work on import* can you please find the median, mode)

In [ ]:
arr

In [ ]:
arr.reshape(3,2)  

In [ ]:
arr.reshape(6,1)  

In [ ]:
arr.reshape(1,6) 

In [ ]:
arr

In [ ]:
arr.reshape(2,4) 

In [ ]:
arr

In [ ]:
arr.reshape(3,2,order='C') 

In [ ]:
arr.reshape(2,3,order='C') 

In [ ]:
arr.reshape(2,3,order='F') # print element with fortran 

In [ ]:
arr.reshape(2,3,order='A') # A almost give you c type output 

In [19]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [ ]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')

In [ ]:
arr.

In [ ]:
arr.reshape(2,3)

In [ ]:
arr.reshape(1,4)  

In [ ]:
arr.reshape(1,6)  

In [ ]:
arr.reshape(6,1)  

In [ ]:
arr.reshape(2,6) 

In [ ]:
arr.reshape(3,3) 

In [ ]:
arr

In [ ]:
arr.reshape(3,2)  

## Indexing

In [ ]:
mat = np.arange(0,100).reshape(10,10) 

In [ ]:
mat

In [ ]:
row = 4
col = 5

In [ ]:
col

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[row,col] 

In [ ]:
mat[4,5] 

In [ ]:
mat

In [ ]:
mat[:]

In [ ]:
col = 6

In [ ]:
mat

In [ ]:
mat[7] # befault it represent to rows

In [ ]:
mat

In [ ]:
# With Slices
mat[:,col] 

In [ ]:
mat

In [ ]:
mat[:, -1]

In [ ]:
mat

In [ ]:
mat[row,:] 

In [ ]:
mat

In [ ]:
mat[:,8]

In [ ]:
mat

In [ ]:
mat[:col] 

In [ ]:
mat[:6]

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[:row]  

In [ ]:
mat

In [ ]:
mat[row:] 

In [ ]:
mat[:]

In [179]:
mat[:,8] 

NameError: name 'mat' is not defined

In [ ]:
mat

In [ ]:
mat[:,-1] 

In [ ]:
mat

In [ ]:
row

In [ ]:
col

In [ ]:
mat[:,col] 

In [ ]:
mat

In [ ]:
mat[1,4]

In [ ]:
mat

In [ ]:
mat[1:4]

In [ ]:
mat

In [ ]:
mat[3:-3]

In [ ]:
mat

In [ ]:
mat[0]

In [ ]:
mat[6]

In [ ]:
mat

In [ ]:
mat[6:]

In [ ]:
mat[:6]

In [ ]:
mat

In [ ]:
mat[5:7]

In [ ]:
mat

In [ ]:
mat[0:10]

In [ ]:
mat

In [ ]:
mat[0:10:3]

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat

In [ ]:
mat[4:]

In [ ]:
mat

In [ ]:
mat[:4]

In [ ]:
mat

In [ ]:
mat[::-1]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-5]

In [ ]:
mat

In [ ]:
mat[2:6]

In [ ]:
mat

In [ ]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

In [ ]:
mat

In [ ]:
mat[0,1]

In [ ]:
mat[1,6]

In [ ]:
mat

In [ ]:
mat[1:6]

In [ ]:
mat[1:]

In [ ]:
mat

In [ ]:
mat[:6]

In [ ]:
mat[0:1]

In [ ]:
mat

In [ ]:
mat[3:5]

In [ ]:
mat[3,5]

In [ ]:
mat

In [ ]:
mat[1:2,2:4] 

In [ ]:
mat

In [ ]:
mat[2:3,2:3] 

In [ ]:
mat

In [ ]:
mat[2:4,3:5]

In [ ]:
mat[3:5,2:4]

In [ ]:
mat

In [ ]:
mat[2:3,4:5]

## Masking

In [ ]:
mat # we also called as filter

In [ ]:
id(mat)

In [ ]:
mat

In [ ]:
mat > 50

In [ ]:
mat[mat==50] 

In [ ]:
mat

In [ ]:
mat == 50

In [ ]:
mat

In [ ]:
a1 = mat[mat<50] 
a1

In [ ]:
mat

In [ ]:
a2 = mat[mat>50] 
a2

In [ ]:
a3 = mat[mat<=50] 
a3

In [ ]:
a4 = mat[mat==50]
a4

# python program to generat otp 

In [ ]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

In [181]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

In [183]:
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(4)
print(f"Your OTP is: {otp}")

Your OTP is: 4131
